export const TEMPLATE_CATEGORIES = [
    "Productivity",
    "Project Management",
    "Education",
    "Business",
    "Personal",
    "Finance",
    "Marketing",
    "Design",
    "Development",
    "Writing",
    "Planning",
    "Tracking",
    "Analytics",
    "CRM",
    "HR",
    "Sales",
    "Operations",
    "Research",
    "Content Creation",
    "Social Media",
];

export const FAMOUS_CATEGORIES = [
    { id: "Productivity", label: "Productivity", icon: "⚡" },
    { id: "Business", label: "Business", icon: "💼" },
    { id: "Education", label: "Education", icon: "🎓" },
    { id: "Personal", label: "Personal", icon: "🏠" },
    { id: "Design", label: "Design", icon: "🎨" },
    { id: "Development", label: "Development", icon: "💻" },
    { id: "Marketing", label: "Marketing", icon: "📈" },
    { id: "Project Management", label: "Project Management", icon: "📅" },
    { id: "Finance", label: "Finance", icon: "💰" },
    { id: "Planning", label: "Planning", icon: "🎯" },
];

export const TEMPLATE_TAGS = [
    "Dashboard",
    "Calendar",
    "Task Management",
    "Note Taking",
    "Database",
    "Kanban",
    "Gantt Chart",
    "Budget",
    "Invoice",
    "CRM",
    "Lead Tracking",
    "Content Calendar",
    "Editorial Calendar",
    "Meeting Notes",
    "Project Tracker",
    "Time Tracking",
    "Expense Tracker",
    "Goal Setting",
    "Habit Tracker",
    "Recipe",
    "Travel Planning",
    "Event Planning",
    "Team Collaboration",
    "Client Management",
    "Inventory",
    "Sales Pipeline",
    "Marketing Campaign",
    "Content Planning",
    "Social Media",
    "Blog",
    "Newsletter",
    "Course",
    "Training",
    "Onboarding",
    "Employee Directory",
    "Performance Review",
    "OKR",
    "Roadmap",
    "Sprint Planning",
    "Bug Tracker",
];

export const NAV_GROUPS = [
    {
        id: "work",
        label: "Work",
        categories: [
            "Project Management",
            "Business",
            "Marketing",
            "Development",
            "Analytics",
            "CRM",
            "HR",
            "Sales",
            "Operations",
        ],
    },
    {
        id: "life",
        label: "Life",
        categories: [
            "Personal",
            "Finance",
            "Planning",
            "Tracking",
            "Writing",
            "Content Creation",
            "Social Media",
        ],
    },
    {
        id: "school",
        label: "School",
        categories: [
            "Education",
            "Research",
        ],
    },
];
